** Bumped sauce connect to 4.3.13 and tweaked waits so it should terminate more gracefully

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -89,8 +89,20 @@ env:
   - goals=verify package=forum use_sc=true it_profile=travis it_browser="microsoftedge" it_browser_version="20.10240" it_platform="Windows 10"
   
 before_script:
-- if [ $use_sc = true ]; then curl -sS https://saucelabs.com/downloads/sc-4.3.12-linux.tar.gz|tar -xzC /tmp/; fi;
-- if [ $use_sc = true ]; then /tmp/sc-4.3.12-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_NUMBER --vm-version dev-varnish -B *.facebook.com --daemonize --pidfile /tmp/sc.pid; fi;
+- if [ $use_sc = true ]; then curl -sS https://saucelabs.com/downloads/sc-4.3.13-linux.tar.gz|tar -xzC /tmp/; fi;
+- if [ $use_sc = true ]; then /tmp/sc-4.3.13-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_NUMBER --vm-version dev-varnish -B *.facebook.com --daemonize --readyfile /tmp/sc.ready --wait-tunnel-shutdown; fi;
+- if [ $use_sc = true ]; then 
+    t=0;
+    while [ ! -f /tmp/sc-ready ]; do 
+      sleep 0.5; 
+      t=$((t+1)); 
+      if [ $t -gt 180 ]; then 
+        killall sc;
+        echo "Unable to get Sauce connection within 3 minutes";
+        exit 1;
+      fi;
+    done;
+  fi;
 script: 
   mvn $goals 
     -P$it_profile 
@@ -102,12 +114,11 @@ script:
     -Dit.browser="$it_browser"
     -Dit.browser.version="$it_browser_version"
     -Dit.platform="$it_platform"
-after_script:
-- if [ -e /tmp/sc.pid ] && [ $use_sc = true ]; then kill `cat /tmp/sc.pid`; fi;
-- if [ -e /tmp/sc.pid ] && [ $use_sc = true ]; then c=0; while kill -0 `cat /tmp/sc.pid`; do sleep 0.5; c=$((c+1)); if [ $c -gt 60 ]; then kill -9 `cat /tmp/sc.pid`; fi; done; fi;
 after_success:
+- if [ $use_sc = true ]; then killall sc; fi;
 - if [ $TRAVIS_BRANCH = 'devel' ]; then python travis/m2conf.py; fi;
 - if [ $TRAVIS_BRANCH = 'devel' ]; then mvn deploy --settings ~/.m2/mySettings.xml; fi;
 after_failure:
+- if [ $use_sc = true ]; then killall sc; fi;
 - cat itests/target/cargo/configurations/wildfly8x/log/server.log
         
